# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MGRmYTZiYjJiMGU0NWFmZjY5NzZmMTAxZDA0OTI3YmUzYThmMzY4YmE4OTEzYzYwYjdmOGQ3ZjU1ZmViNGVlNzUzNDU1NDUwODJkYjQwNzc0MjM1MGVkYTJlYzE2ZTdjMDc2ZWQ0ZjAwNTQ0ZTI2NTRhNTdkMjI0ZDljYmExMTk=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
